### ISSUE TITLE
The plugins doesn't work now ...

### ISSUE THREAD

**Issue by diygun** [PyramidTeam/Portal#5]
[Server] [23:39:50] [CRITICAL]: ReflectionException: "Class Portal\EntityMoveEvent does not exist" (EXCEPTION)

**Comment by legoboy0215** [comment]
EntityMoveEvent is now deprecated. Use PlayerMoveEvent.

**Comment by diygun** [comment]
i use PlayerMove Event but I can't using this plugins ....
I need change PlayerMoveEvent on witch fiel

**Comment by diygun** [comment]
Please help me i Can't fixe it 
...
