### ISSUE TITLE
Portal doesn't work on Elywing 1.0Core API:3.0

### ISSUE THREAD

**Issue by bzdnd** [PyramidTeam/Portal#6]
09:06:08 | Elywing thread:INFO > 
                ____          
               |  __|_              _
               | |__| |      _    _(_)_ __   ___
               |  __| |_   _| |  | | | '_ \ / _ \
               | |__| | | | | |/\| | | | | | (_) |
               |____|_|\ \/ \__/\__/_|_| |_|\___ |
                       _|  /                 __| |
                      |___/                 |___/

	A stable v1.0.0 alpha fork of PocketMine-MP (pmmp).
			Modified by H4PM.
	    Source code: https://github.com/H4PM/Elywing
	
09:06:08 | Elywing thread:INFO > Loading properties and configuration...
09:06:08 | Elywing thread:WARNING > SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
09:06:08 | Elywing thread:WARNING > The server will make no attempt to authenticate usernames. Beware.
09:06:08 | Elywing thread:WARNING > While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
09:06:08 | Elywing thread:WARNING > To change this, set "online-mode" to "true" in the server.properties file.
09:06:08 | Elywing thread:INFO > Selected English (eng) as the base language
09:06:08 | Elywing thread:INFO > Opening server on 0.0.0.0:19132
09:06:08 | Elywing thread:INFO > Elywing is distributed under the GPL License version 3 and later
09:06:09 | Elywing thread:INFO > Loading recipes...
09:06:09 | Elywing thread:INFO > Loading EconomyAPI v2.0.9
09:06:09 | Elywing thread:INFO > Loading SWorld v2.0.0
09:06:09 | Elywing thread:INFO > Loading PureEntitiesX v0.1.1_dev

Warning: Declaration of revivalpmmp\pureentities\entity\BaseEntity::entityBaseTick($tickDiff = 1) should be compatible with pocketmine\entity\Living::entityBaseTick($tickDiff = 1, $EnchantL = 0) in phar:///storage/emulated/0/PocketMine/plugins/phar_PureEntitiesX-master_YkqVRtFFlc1HCyz.phar/src/revivalpmmp/pureentities/entity/BaseEntity.php on line 225
09:06:09 | Elywing thread:INFO > [PureEntitiesX] You're Running PureEntitiesX v0.1.1_dev
09:06:09 | Elywing thread:INFO > [PureEntitiesX] The Original Code for this Plugin was Written by milk0417. It is now being maintained by RevivalPMMP for PMMP 'Unleashed'.
09:06:09 | Elywing thread:INFO > Loading PEXProtection v0.1.0
09:06:09 | Elywing thread:INFO > Loading DevTools v1
09:06:09 | Elywing thread:INFO > Loading WorldEditPotato v1.5
09:06:09 | Elywing thread:INFO > Loading Slapper v1.3.3
09:06:09 | Elywing thread:INFO > Loading Portal v3.0.1
09:06:09 | Elywing thread:CRITICAL > Could not load plugin 'ArtisticRedStoneMusic1': Unknown dependency
09:06:09 | Elywing thread:CRITICAL > Could not load plugin 'ArtisticRedStoneMusic1': Unknown dependency
09:06:09 | Elywing thread:INFO > Loading MyPlot v1.1.3
09:06:09 | Elywing thread:CRITICAL > Could not load plugin 'ArtisticRedStoneMusic1': Unknown dependency
09:06:09 | Elywing thread:CRITICAL > Could not load plugin 'ArtisticRedStoneMusic1': Circular dependency detected
09:06:09 | Elywing thread:INFO > Enabling PureEntitiesX v0.1.1_dev
09:06:09 | Elywing thread:INFO > [PureEntitiesX] Plugin has been enabled
09:06:09 | Elywing thread:INFO > [PureEntitiesX] You're running PureEntitiesX Dev!
09:06:09 | Elywing thread:INFO > Enabling DevTools v1
09:06:09 | Elywing thread:INFO > Loading source plugin send v1.0.0
09:06:09 | Elywing thread:INFO > [DevTools] Registered folder plugin loader
09:06:09 | Elywing thread:INFO > Enabling MyPlot v1.1.3
09:06:09 | Elywing thread:NOTICE > [MyPlot] Loading...
09:06:10 | Elywing thread:NOTICE > [MyPlot] Enabled!
09:06:10 | Elywing thread:INFO > Enabling send v1.0.0
09:06:10 | Elywing thread:INFO > [send] ===底部信息加载中
09:06:10 | Elywing thread:INFO > [send] ===底部信息加载成功===
09:06:10 | Elywing thread:INFO > Preparing level "world"
09:06:10 | Elywing thread:INFO > Preparing level "nether"
09:06:10 | Elywing thread:INFO > Enabling EconomyAPI v2.0.9
09:06:10 | Elywing thread:NOTICE > [EconomyAPI] Auto save has been set to interval : 10 min(s)
09:06:10 | Elywing thread:INFO > [EconomyAPI] Checking for updates... It may be take some while.
09:06:10 | Elywing thread:NOTICE > [EconomyAPI] 
09:06:10 | Elywing thread:INFO > Enabling SWorld v2.0.0
09:06:10 | Elywing thread:INFO > SWorld loaded!
09:06:10 | Elywing thread:INFO > [SWorld] 正在加载世界：jm
09:06:10 | Elywing thread:INFO > Preparing level "jm"
09:06:10 | Elywing thread:INFO > [SWorld] 正在加载世界：Candy
09:06:10 | Elywing thread:INFO > Preparing level "Candy"
09:06:10 | Elywing thread:INFO > Enabling PEXProtection v0.1.0
09:06:10 | Elywing thread:INFO > PEXProtector activated!
09:06:10 | Elywing thread:INFO > Enabling WorldEditPotato v1.5
09:06:10 | Elywing thread:INFO > Enabling Slapper v1.3.3
09:06:10 | Elywing thread:INFO > Enabling Portal v3.0.1
09:06:10 | Elywing thread:CRITICAL > ReflectionException: "Class Portal\EntityMoveEvent does not exist" (EXCEPTION) in "/src/pocketmine/plugin/PluginManager" at line 752
09:06:10 | Elywing thread:INFO > Disabling Portal v3.0.1
09:06:10 | Elywing thread:NOTICE > Your genisys.yml needs update
09:06:10 | Elywing thread:NOTICE > Current Version: 18   Latest Version: 22
09:06:10 | Elywing thread:INFO > Starting GS4 status listener
09:06:10 | Elywing thread:INFO > Setting query port to 19132
09:06:10 | Elywing thread:INFO > Query running on 0.0.0.0:19132
09:06:10 | Elywing thread:INFO > Default game type: Survival Mode
09:06:10 | Elywing thread:INFO > Done (2.817s)! For help, type "help" or "?"

**Comment by legoboy0215** [comment]
This is not maintained anymore.

**Comment by bzdnd** [comment]
all right。。
